### ISSUE TITLE
Some questions for Fig5.

### ISSUE THREAD

**Issue by FlamingoPg** [mit-han-lab/distrifuser#1]
Hi, nice work and I really love it. 
My question is that when reading the paper, I noticed that in the demonstration images at the very beginning of the paper, the effects of the generated images with the original equipment and DPP=8 are exactly the same. However, in Fig. 5, there are some subtle differences, such as the parrot's eyes and the child's background. What might be the reason for this? Is it the error caused by using statistical estimation in the GN layer?
Thanks

**Comment by lmxyy** [comment]
Thanks for your interest. 
There may be some minor differences between the results from the original model and DistriFusion, as it reuses the stale activations to hide communication. In Figure 1, such minor differences also exist, such as the sail in the ship example.
