### ISSUE TITLE
Measuring Communication Amount

### ISSUE THREAD

**Issue by tonyluozn** [mit-han-lab/distrifuser#10]
Hi, thanks for the great work! I'm wondering how is the communication amount in Table 2 of the paper is calculated. Are those calculations available in the evaluation script?

**Comment by lmxyy** [comment]
In this [`PatchParallelismCommManager`](https://github.com/mit-han-lab/distrifuser/blob/3b1ecd49e8ca6244689a5b9e0fa0c742f016e160/distrifuser/utils.py#L155), we print the buffer size on each device (`self.numel`). You can enable the profiling with `verbose=True` when initializing the [`distri_config`](https://github.com/mit-han-lab/distrifuser/blob/3b1ecd49e8ca6244689a5b9e0fa0c742f016e160/scripts/sdxl_example.py#L6).

For AllGather, when using ring AllGather, the communication amount is $s \times (n-1) \times 2$, where $s$ is the buffer size, $n$ is the number of devices and 2 stands for 2 bytes for FP16 precision.

**Comment by lmxyy** [comment]
For AllReduce, when using ring AllReduce, the communication amount is $s \times \frac{n-1}{n} \times 2 \times 2$. The first 2 stands for the 2 rounds of ring AllReduce and the second 2 stands for 2 bytes for FP16 precision. For Tensor Parallelism, our code does not support printing the buffer size `s` for now. You can easily calculate it by summing up all the AllReduced tensor's `numel` in [`attention.py`](https://github.com/mit-han-lab/distrifuser/blob/3b1ecd49e8ca6244689a5b9e0fa0c742f016e160/distrifuser/modules/tp/attention.py#L159), [`conv.py`](https://github.com/mit-han-lab/distrifuser/blob/3b1ecd49e8ca6244689a5b9e0fa0c742f016e160/distrifuser/modules/tp/conv2d.py#L52), [`feed_forward.py`](https://github.com/mit-han-lab/distrifuser/blob/3b1ecd49e8ca6244689a5b9e0fa0c742f016e160/distrifuser/modules/tp/feed_forward.py#L77) and [`resnet.py`](https://github.com/mit-han-lab/distrifuser/blob/3b1ecd49e8ca6244689a5b9e0fa0c742f016e160/distrifuser/modules/tp/resnet.py#L189).

**Comment by lmxyy** [comment]
You can refer to our [efficientml.ai slides](https://www.dropbox.com/scl/fi/vn3n0b2r5fgcc0j0vrh0k/lec17.pdf?rlkey=8e7dg5lduuqq62kr7flhik23g&e=1&dl=0) (page 50) for these communication primitives.
