### ISSUE TITLE
Odd number of GPUs

### ISSUE THREAD

**Issue by FlaviuRadulescu** [mit-han-lab/distrifuser#15]
Hi, is there any particular reason why you can't have an odd number (or any number) of GPUs?

**Comment by lmxyy** [comment]
Because the image latent size is often the multiplier of two. If the GPU number is odd, the patch size is not that easy to split, but not impossible.

**Comment by FlaviuRadulescu** [comment]
do you have a recommendation on how to split it

**Comment by lmxyy** [comment]
You can choose the height of the latent to be a multiplier of the number of GPUs.
