### ISSUE TITLE
Chaos Picture

### ISSUE THREAD

**Issue by Qlalq** [mit-han-lab/distrifuser#16]
I only changed the resolution of the image, but the output is garbled!
I would like to know why this is?
I'm using RTX 2080 Ti * 2 cards and changed the resolution of the image in sdxl_example.py to 256x256
Here is the output astronaut.png
![astronaut](https://github.com/mit-han-lab/distrifuser/assets/130260455/ed9ac0dd-921c-419d-8ff1-675ea5ad278d)

**Comment by lmxyy** [comment]
Did you verify the code works on 1k image?

**Comment by lmxyy** [comment]
It seems that it is because SDXL cannot handle small resolutions, as stated [here](https://github.com/huggingface/diffusers/blob/c586aadef6bb66d355fa40a2b95a0bea8a6fe79c/src/diffusers/pipelines/stable_diffusion_xl/pipeline_stable_diffusion_xl.py#L883).
