### ISSUE TITLE
Why do we need to set n_device_per_batch like this？

### ISSUE THREAD

**Issue by LHQUer** [mit-han-lab/distrifuser#19]
the python file is /distrifuser/distrifuser/utils.py, and I can't understand why do we need to set variable n_device_per_batch like "n_device_per_batch = world_size // 2".  Is n_device_per_batch  means that N devices for one patch as described in the paper?
Partial code is as follows：
```
if do_classifier_free_guidance and split_batch:
        n_device_per_batch = world_size // 2
        if n_device_per_batch == 0:
            n_device_per_batch = 1
        else:
            n_device_per_batch = world_size

        self.n_device_per_batch = n_device_per_batch
```

**Comment by LHQUer** [comment]
I can't understand why n_device_per_batch = world_size // 2

**Comment by lmxyy** [comment]
Hi! Diffusion model inference often uses [classifier-free guidance](https://arxiv.org/abs/2207.12598), where the batch size will double. So here, we first the split the batch and within a batch we use displaced patch parallelism.

**Comment by LHQUer** [comment]
> Hi! Diffusion model inference often uses [classifier-free guidance](https://arxiv.org/abs/2207.12598), where the batch size will double. So here, we first the split the batch and within a batch we use displaced patch parallelism.

Get it ! Thank you so much!

**Comment by LHQUer** [comment]
Another question，if I can understand what you say in this way: if we have world_size=2 devices totally and they will be split in two parts. Every part(half of batch) having one device. So there is no patch  parallelism in this case ?
If we want to set patch parallelism, we must set  world_size>=4 so that within 2 devices  at least for one patch?

> Hi! Diffusion model inference often uses [classifier-free guidance](https://arxiv.org/abs/2207.12598), where the batch size will double. So here, we first the split the batch and within a batch we use displaced patch parallelism.

Another question，if I can understand what you say in this way: if we have world_size=2 devices totally and they will be split in two parts. Every part(half of batch) having one device. In other word, just one device for one patch. So there is no patch  parallelism in this case.
If we want to set patch parallelism, we must set  world_size>=4 so that within 2 devices  at least for one patch?
