### ISSUE TITLE
What is the difference between ‘full_sync’ mode and ‘sync_gn’ and ‘corrected_async_gn’?

### ISSUE THREAD

**Issue by ZijianZhouPro** [mit-han-lab/distrifuser#23]
Hello, what is the difference between ‘full_sync’ mode and ‘sync_gn’ and ‘corrected_async_gn’?
![image](https://github.com/user-attachments/assets/55c65a7b-5780-4f15-b385-73d8d3b01e98)

**Comment by lmxyy** [comment]
`full_sync` means using synchronous communication for every single layer, which means the naive patch parallelism. `sync_gn` means we only synchronous communication for the groupnorm (GN) while others are all displaced patch parallelism. `corrected_async_gn` is the one we mentioned in the paper for GN.
