### ISSUE TITLE
Using video cards with different architectures

### ISSUE THREAD

**Issue by DmitryVN** [mit-han-lab/distrifuser#3]
Can I use it for a tesla p40 and 3060 ti graphics card? (or 30-s with 40-s series)
thanks

**Comment by lmxyy** [comment]
It depends on your communication bandwidth between GPUs. If it is not large enough, the communication cannot be hidden in the computation, which will slow down the inference. Typically, an NVLink is essential. However, it is quite accessible nowadays. You can find it [here](https://www.google.com/search?q=nvlink+price&client=safari&sca_esv=5d95fa5235c39ff3&channel=mac_bm&sxsrf=ACQVn08LW6j3Rloc33UK_CHLMab2M109zw%3A1709585331707&source=hp&ei=szPmZa6PKeCP2roPu8eX-AQ&iflsig=ANes7DEAAAAAZeZBw351Dg0Q2UhgRVwBY_w6c3AaXWxO&ved=0ahUKEwjutKHTvduEAxXgh1YBHbvjBU8Q4dUDCBc&uact=5&oq=nvlink+price&gs_lp=Egdnd3Mtd2l6IgxudmxpbmsgcHJpY2UyChAjGIAEGIoFGCcyBhAAGBYYHjIGEAAYFhgeMgYQABgWGB4yCxAAGIAEGIoFGIYDMgsQABiABBiKBRiGA0iFD1AAWNENcAB4AJABAJgBkQKgAbMNqgEFMy44LjG4AQPIAQD4AQGYAgygAtsNwgIOEC4YgAQYigUYsQMYgwHCAg4QLhiABBixAxjHARjRA8ICCxAuGIAEGMcBGNEDwgIIEC4YgAQYsQPCAhAQABiABBiKBRhDGLEDGIMBwgIWEC4YQxiDARjHARixAxjRAxiABBiKBcICEBAAGIAEGBQYhwIYsQMYgwHCAgoQABiABBiKBRhDwgIQEC4YgAQYigUYQxjHARjRA8ICDRAAGIAEGIoFGEMYsQPCAgUQABiABMICChAAGIAEGBQYhwLCAggQABiABBixA8ICCxAAGIAEGIoFGJECwgIIEC4YgAQY5QTCAggQABiABBjLAcICDhAuGIAEGIoFGJECGOUEwgIIEAAYFhgeGA-YAwCSBwUzLjguMaAHlmc&sclient=gws-wiz).
