### ISSUE TITLE
Can distrifuser support SD v2-1 or v1-5?

### ISSUE THREAD

**Issue by czg1225** [mit-han-lab/distrifuser#5]
Thanks for your great work! I have two questions.
1. Can distrifuser support sd v2-1 or v1-5 for now?
2. How did you implement ParaDiGMS on SDXL? I found there is no code for accelerating SDXL in ParaDiGMS's original code repository.

Thanks!

**Comment by lmxyy** [comment]
Hi, I just supported SD1.4/1.5 or SD2. Please refer to [sd_example.py](https://github.com/mit-han-lab/distrifuser/blob/main/scripts/sd_example.py). Note that our experiments are mainly conducted on SDXL. We have not tested the performance regarding both the quality and efficiency of SD.

ParaDiGMS is just a sampler and we manually support it on SDXL. All you need to do is change the UNets output from SD to UNet outputs from SDXL.
