### ISSUE TITLE
Questions about employing distrifuser to SD2.1/1.5

### ISSUE THREAD

**Issue by czg1225** [mit-han-lab/distrifuser#7]
Hi, 
I have tried ``scrips/sd_example.py``. It works well when I use 2 GPUs. However, when I use 4 or more GPUs, the output of SD will be a totally black image.  Is this a bug or distrifuser cannot process such low-resolution (768*768, 512*512) images so far?

**Comment by lmxyy** [comment]
Could you change the `mode` of this [line](https://github.com/mit-han-lab/distrifuser/blob/f1f45fba5a6a2ccef15e811625fa5176c381aa19/scripts/sd_example.py#L6) to `sync_gn` to see if it works?

**Comment by czg1225** [comment]
It's solved, Thanks!

**Comment by lmxyy** [comment]
For better speed, you can also try `separate_gn` for better speed. `stale_gn` and `correct_async_gn` seem to have some bugs when the resolution is small. I will let you know when I solve this.
