### ISSUE TITLE
Assertion error when setting do_classifier_free_guidance to false

### ISSUE THREAD

**Issue by xiuyuz** [mit-han-lab/distrifuser#8]
Hi! Thank you for open sourcing distrifuser. There might be a bug in the current implementation when setting do_classifier_free_guidance to false. I have tried the combinations (do_classifier_free_guidance=False, split_batch=True) and (do_classifier_free_guidance=False, split_batch=False) on 4 GPUs. All of them were terminated by an assertion error. 

An example is shown below:

[rank2]:   File "xxx/distrifuser/models/distri_sdxl_unet_pp.py", line 89, in forward
[rank2]:     assert static_inputs["sample"].shape == sample.shape
[rank2]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank2]: AssertionError

Thanks.

**Comment by lmxyy** [comment]
What detailed command did you use?

**Comment by xiuyuz** [comment]
I used

torchrun --nproc_per_node=4 scripts/sdxl_example.py

and I modified sdxl_example.py to pass in do_classifier_free_guidance=False when initializing.

**Comment by lmxyy** [comment]
Please pass `guidance_scale=1` in this [line](https://github.com/mit-han-lab/distrifuser/blob/c71cba0c30bd13c131edb01b207014af19559ba3/scripts/sdxl_example.py#L17) when you disable the classifier-free guidance. I've also updated our code to auto-set guidance to 1 when you disable the classifier-free guidance.
