### ISSUE TITLE
vscode debug launch.json file

### ISSUE THREAD

**Issue by Kyuseok-nam** [mit-han-lab/distrifuser#9]
Hi, I'm trying to debug distrifusion using vscode. 

I would like to run this command "torchrun --nproc_per_node=$N_GPUS scripts/sdxl_example.py" 

using this launch.json file but it doesn't seem to work.
{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Python Debugger: Current File",
            "type": "debugpy",
            "request": "launch",
            "program": "${command:python.interpreterPath}",
            "args": [
                "-m",
                "torch.distributed.launch",
                "--nproc_per_node=2",
                "scripts/sdxl_example.py"
            ],
            "console": "integratedTerminal"
        }
    ]
}

Is there any way I could debug the code? 
I would really appreciate some help.

**Comment by lmxyy** [comment]
I am not familiar with your debugging tool. Typically, I directly print the debug info in the code for debugging. What kind of bugs are you debugging?

**Comment by Kyuseok-nam** [comment]
Thank you for the reply!
I'm currently using vscode, and I'm just trying to go through the code line by line trying to figure out what's exactly happening inside the functions or the value of variables.

**Comment by lmxyy** [comment]
I see. I think for a multi-process program, it is not that easy to view it step by step. You may also want to pass `use_cuda_graph=False` in this [line](https://github.com/mit-han-lab/distrifuser/blob/3b1ecd49e8ca6244689a5b9e0fa0c742f016e160/scripts/sdxl_example.py#L6), which disable the CUDAGraph and lets you view the PyTorch forward, although it will slow down the parallelism.
